source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.9'

gem 'rails', '~> 6.1.4'
gem 'sqlite3', '~> 1.4'
gem 'puma', '~> 5.0'
gem 'bootsnap', '>= 1.4.4', require: false

gem 'react_query_builder', path: '../../../react_query_builder'

gem 'bootstrap'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'react-rails'
gem 'simple_form'
gem 'reform'
gem 'reform-rails'

group :development, :test do
	gem 'scenic'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
